export const library = {
  songs: [
     {'name': 'I\'m Ready', 'id': 1},
     {'name': 'Roses - Imanbek Remix', 'id': 2},
     {'name': 'Blinding Lights', 'id': 3},
     {'name': 'Toosie Slide', 'id': 4},
     {'name': 'Blueberry Faygo', 'id': 5},
     {'name': 'Don\'t Start Now', 'id': 6},
     {'name': 'Say So', 'id': 7},
     {'name': 'death bed (coffee for your head)', 'id': 8},
     {'name': 'Sunday Best', 'id': 9},
     {'name': 'Supalonely', 'id': 10},
     {'name': 'Intentions', 'id': 11},
     {'name': 'Break My Heart', 'id': 12},
     {'name': 'Boyfriend', 'id': 13},
     {'name': 'The Box', 'id': 14},
     {'name': 'ily (i love you baby)', 'id': 15},
     {'name': 'In Your Eyes', 'id': 16},
     {'name': 'Savage', 'id': 17},
     {'name': 'Falling', 'id': 18},
     {'name': 'ROCKSTAR', 'id': 19},
     {'name': 'Adore You', 'id': 20},
     {'name': 'Like It Is', 'id': 21},
     {'name': 'WHATS POPPIN', 'id': 22},
     {'name': 'Level of Concern', 'id': 23},
     {'name': 'Physical', 'id': 24},
     {'name': 'BELIEVE IT', 'id': 25},
     {'name': 'Breaking Me', 'id': 26},
     {'name': 'Know Your Worth', 'id': 27},
     {'name': 'Salt', 'id': 28},
     {'name': 'CITY OF ANGELS', 'id': 29},
     {'name': 'Life is Good', 'id': 30},
     {'name': 'My Oh My', 'id': 32},
     {'name': 'Selfish', 'id': 33},
     {'name': 'If the World Was Ending', 'id': 34},
     {'name': 'ROXANNE', 'id': 35},
     {'name': 'Gimme Love', 'id': 36},
     {'name': 'You should be sad', 'id': 37},
     {'name': 'Before You Go', 'id': 38},
     {'name': 'This City', 'id': 39},
     {'name': 'In Your Eyes', 'id': 40},
     {'name': 'Circles', 'id': 41},
     {'name': 'Walk Em Down', 'id': 42},
     {'name': 'What If I Told You That I Love You', 'id': 43},
     {'name': 'Stupid Love', 'id': 44},
     {'name': 'Maniac', 'id': 45},
     {'name': 'Moral of the Story', 'id': 46},
     {'name': 'Dance Monkey', 'id': 47},
     {'name': 'Turks', 'id': 48}
  ],
  artists: [
     {'name': 'Sam Smith', 'id': 1},
     {'name': 'Demi Lovato', 'id': 2},
     {'name': 'The Weeknd', 'id': 3},
     {'name': 'Drake', 'id': 4},
     {'name': 'Dua Lipa', 'id': 5},
     {'name': 'Doja Cat', 'id': 6},
     {'name': 'Surfaces', 'id': 7},
     {'name': 'Justin Bieber', 'id': 8},
     {'name': 'Selena Gomez', 'id': 9},
     {'name': 'Harry Styles', 'id': 10},
     {'name': 'Jonas Brothers', 'id': 11},
     {'name': 'Halsey', 'id': 12},
     {'name': 'Sam Hunt', 'id': 13},
     {'name': 'Camila Cabello', 'id': 14},
     {'name': 'Sam Hunt', 'id': 15},
     {'name': '5 Seconds of Summer', 'id': 16}
  ],
  playlists: [
     {'name': 'Viva Latino', 'id': 1},
     {'name': 'Spain Top 50', 'id': 2},
     {'name': 'Greece Top 50', 'id': 3},
     {'name': 'Today\'s Top Hits', 'id': 4},
     {'name': 'Tailgate with your Dad', 'id': 5},
     {'name': 'Disney Hits', 'id': 6},
     {'name': 'United States Top 50', 'id': 7},
     {'name': 'Eggplants and Sangria', 'id': 8},
     {'name': '1990\'s - 2000\'s', 'id': 9},
     {'name': 'Greek', 'id': 10},
     {'name': 'ES', 'id': 11},
     {'name': 'GR', 'id': 12}
  ],
  albums: [
     {'name': 'Changes', 'artist': 'Justin Bieber', 'id': 1},
     {'name': 'Romance', 'artist': 'Camila Cabello', 'id': 2},
     {'name': 'Fine Line', 'artist': 'Harry Styles', 'id': 3},
     {'name': 'Hollywood\'s Bleeding', 'artist': 'Post Malone', 'id': 4},
     {'name': 'Happiness Begins', 'artist': 'Jonas Brothers', 'id': 5},
     {'name': 'Tell Me You Love Me', 'artist': 'Demi Lovato', 'id': 6},
     {'name': 'Calm', 'artist': '5 Seconds of Summer', 'id': 7},
     {'name': 'After Hours', 'artist': 'The Weeknd', 'id': 8},
     {'name': 'Manic', 'artist': 'Halsey', 'id': 9},
     {'name': 'Rare', 'artist': 'Selena Gomez', 'id': 10},
     {'name': 'Future Nostalgia', 'artist': 'Dua Lipa', 'id': 11},
     {'name': 'Southside', 'artist': 'Sam Hunt', 'id': 12}
  ]
}
